services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=super_strong_password
      - POSTGRES_USER=crypto_admin
      - POSTGRES_DB=crypto_db