export enum Settings {
  COINGECKO_API_KEY = 'COINGECKO_API_KEY',
  COINGECKO_API_BASE_URL = 'COINGECKO_API_BASE_URL',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_LOGGING = 'DATABASE_LOGGING',
}
