name: Publish artifacts

on:
  push:
    tags: 
      - '*'

jobs:  
  publish-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker build
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
      run: |
        BUILD_DATE="$(date -R)"
        
        if [ "$GITHUB_REF_NAME" ]; then
          REF_TYPE="Tag"
          GIT_REF="$GITHUB_REF_NAME"
        else
          REF_TYPE="Branch"
          GIT_REF="$GITHUB_REF_NAME"
        fi

        test -d public || mkdir public
        sed \
          -e "s%__BUILD_DATE__%$BUILD_DATE%g" \
          -e "s%__GIT_SHA__%$GITHUB_SHA%g" \
          -e "s%__REF_TYPE__%$REF_TYPE%g" \
          -e "s%__GIT_REF__%$GIT_REF%g" \
          tmpl/v.html > public/v.html
          
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build --file Dockerfile --tag fjbarrena/crypto-asset-manager:$GITHUB_REF_NAME .
        docker build --file Dockerfile --tag fjbarrena/crypto-asset-manager .
    - name: Check image vulnerabilities
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
      run: |
        echo "Installing grype"
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
        
        grype fjbarrena/crypto-asset-manager:$GITHUB_REF_NAME --fail-on high

    - name: Push image to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
      run: |
        docker push fjbarrena/crypto-asset-manager:$GITHUB_REF_NAME
        docker push fjbarrena/crypto-asset-manager:latest    